### ISSUE TITLE
提问：获取用户关注列表的方法get_followings_g貌似出现问题了

### ISSUE THREAD

**Issue by freedomgod** [Passkou/bilibili-api#147]
今早发现在我的程序的user.get_followings_g(uid=701611630, order="asc", verify=verify)地方出现错误。测试如下：
```
from bilibili_api import Verify
from bilibili_api import user
import json


with open('previous_cookie.json', 'r') as f:
    data = json.load(f)
    sessdata = data['sessdata']
    csrf = data['csrf']

verify = Verify(sessdata=sessdata, csrf=csrf)
my_like_up = user.get_followings_g(uid=701611630, order="asc", verify=verify)  # 获取到关注的up主信息
list(my_like_up)
```
报错是
```
Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\Bilibili-forward\bilibili_auto_forwarding\subscirbe_operation.py", line 13, in <module>
    next(my_like_up)
  File "D:\Python39\lib\site-packages\bilibili_api\user.py", line 504, in get_followings_g
    data = get_followings_raw(uid=uid, order=order, pn=page, verify=verify)
  File "D:\Python39\lib\site-packages\bilibili_api\user.py", line 486, in get_followings_raw
    data = utils.get(url=api["url"], params=params, cookies=verify.get_cookies())
  File "D:\Python39\lib\site-packages\bilibili_api\utils.py", line 415, in get
    resp = request("GET", url=url, params=params, cookies=cookies, headers=headers, data_type=data_type, **kwargs)
  File "D:\Python39\lib\site-packages\bilibili_api\utils.py", line 375, in request
    req = requests.request(method, **st)
  File "D:\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\Python39\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "D:\Python39\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "D:\Python39\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "D:\Python39\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "D:\Python39\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\Python39\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Python39\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname
```
用user的get_followings_g获取关注列表返回的应该是个生成器<generator object get_followings_g at 0x000001B19EDC1CF0>，但我不明白为什么会报上面这个错，以前是没有问题的。
版本是4.0.4

**Comment by Passkou** [comment]
你这个是 SSL 出错了，我这运行正常，检查一下你是不是开了代理什么的

**Comment by freedomgod** [comment]
哦，的确是，感谢！
