### ISSUE TITLE
调用user.get_dynamic_raw()函数出错

### ISSUE THREAD

**Issue by Yang161941** [Passkou/bilibili-api#152]
环境：Python 3.7.9
bilibili_api版本：bilibili-api              4.1.0
以下是我操作的步骤：
```python
>>> import bilibili_api
>>> bilibili_api.request_settings = {
...     "use_https": True,
...     "proxies": None
... }
>>> verify = bilibili_api.Verify("******", "******")
>>> bilibili_api.user.get_dynamic_raw(verify)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\bilibili_api\user.py", line 322, in get_dynamic_raw
    data = utils.get(url=api["url"], params=params, cookies=verify.get_cookies())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\bilibili_api\utils.py", line 424, in get
    resp = request("GET", url=url, params=params, cookies=cookies, headers=headers, data_type=data_type, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\bilibili_api\utils.py", line 400, in request
    raise exceptions.BilibiliException(con["code"], msg)
bilibili_api.exceptions.BilibiliException: 错误代码：500003, 信息：请求数据发生错误，请刷新或稍后重试
>>> verify.check()
{'code': 0, 'message': '0'}
>>> 
```

**Comment by tx510** [comment]
get_dynamic_raw(uid)

**Comment by Yang161941** [comment]
谢谢，解决问题了
