### ISSUE TITLE
【漏洞】{回复评论的AIP貌似被玩坏了}

### ISSUE THREAD

**Issue by MrGuoRanDuo** [Passkou/bilibili-api#195]
**Python 版本：** 3.7.6

**模块版本：*5.1.2

**运行环境：** Windows

**模块路径：** bilibili_api.xxxx

**报错信息：**

```
测试回复视频
Traceback (most recent call last):
  File "F:/Python/bilibili-api/test.py", line 46, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "c:\users\**\appdata\local\programs\python\python37\lib\asyncio\base_events.py", line 583, in run_until_complete
    return future.result()
  File "F:/Python/bilibili-api/test.py", line 39, in main
    credential=credential)
  File "F:\Python\bilibili-api\bilibili_api\comment.py", line 231, in send_comment
    return await request("POST", api["url"], data=data, credential=credential)
  File "F:\Python\bilibili-api\bilibili_api\utils\network.py", line 153, in request
    raise ResponseCodeException(code, msg, resp_data)
bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：-400，信息：请求错误。

Process finished with exit code 1

```

**报错代码：**

```python
    print("测试回复视频")
    result = await comment.send_comment("测试" + str(random.random()), oid=AID, type_=comment.ResourceType.VIDEO,
                                        credential=credential)
    global comment_id
    comment_id = result["rpid"]
    await asyncio.sleep(1)
```

---

在此处写正文   回复评论的AIP貌似被玩坏了

**Comment by MrGuoRanDuo** [comment]
修改标题

**Comment by MrGuoRanDuo** [comment]
搞错了
