### ISSUE TITLE
【漏洞】{接口返回错误代码：21001，信息：参数错误。

### ISSUE THREAD

**Issue by googidaddy** [Passkou/bilibili-api#203]
**Python 版本：** 3.8

**模块版本：** x.x.x

**运行环境：** Linux

**模块路径：** bilibili_api.xxxx

**报错信息：接口返回错误代码：21001，信息：参数错误

```
这里填写报错信息
```

**报错代码：**

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/main.py", line 24, in upload
```

---

代码在本地上传视频是没问题，放到服务器端就不行了，在这里res = await uploader.start() 发生了错误，但是错误信息print出来是接口参数问题？？

**Comment by googidaddy** [comment]
对不起，我傻逼了，传字典的时候没注意看，今天排查了一下午，把一个`string`传值给了一个`int`，弄半天还是眼的问题，经典typo
